version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - DB_PATH=/app/data/relatorio_dashboard.db
      - PORT=8001
      - HOST=0.0.0.0
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 